// Prueba de navegador con Supabase simulado: nunca accede a datos reales.
// Uso: node tests/preventivos-ui.mjs <playwright/index.mjs> <carpeta capturas>
import { build } from 'esbuild'
import { createServer } from 'node:http'
import { readFile } from 'node:fs/promises'
import { pathToFileURL } from 'node:url'
import { join } from 'node:path'
import assert from 'node:assert/strict'
import XLSX from 'xlsx'
import { catalogoDesdeMatriz } from '../src/utils/preventivos.js'
const { chromium } = await import(pathToFileURL(process.argv[2]).href)
const libro=XLSX.readFile('src/Mantenimientos.xlsx')
const catalogo=catalogoDesdeMatriz(XLSX.utils.sheet_to_json(libro.Sheets[libro.SheetNames[0]],{header:1,defval:''}))
const local=catalogo.find(l=>l.activo&&l.marca==='GRANJERO'&&l.meses.includes(10))
const backend=`
const usuario='00000000-0000-0000-0000-000000000002';
let ordenes=JSON.parse(sessionStorage.getItem('ordenes')||'[]'),declaraciones=[],fallar=false;
let exclusiones=JSON.parse(sessionStorage.getItem('exclusiones')||'[]'),historialExclusiones=JSON.parse(sessionStorage.getItem('historialExclusiones')||'[]');
let locales=JSON.parse(sessionStorage.getItem('locales')||'null')||${JSON.stringify(catalogo.map(l=>({...l,activo_calendario:l.activo,activo_manual:null,revision_estado:0,revision_catalogo:0,origen_manual:false})))},cierres=JSON.parse(sessionStorage.getItem('cierres')||'[]');
const copiar=d=>JSON.parse(JSON.stringify(d));
export function setOrdenes(d){ordenes=d;sessionStorage.setItem('ordenes',JSON.stringify(d))}
export function setFallar(d){fallar=d}
function query(datos){return {select(){return this},order(){return this},eq(){return this},ilike(){return this},limit(){return this},async maybeSingle(){return {data:datos[0]||null,error:null}},async range(i,f){return {data:copiar(datos.slice(i,f+1)),error:null}},then(resolve,reject){return Promise.resolve({data:copiar(datos),error:null}).then(resolve,reject)}}}
export const supabase={auth:{async getSession(){return {data:{session:{user:{id:usuario,email:'ana@example.test'}}}}},onAuthStateChange(){return {data:{subscription:{unsubscribe(){}}}}},async signOut(){}},
from(tabla){if(tabla==='preventivos_ordenes_exclusiones')return query(exclusiones);if(tabla==='preventivos_exclusiones_historial')return query(historialExclusiones);if(tabla==='viaticos_admins')return query([]);if(tabla==='vac_empleados')return query([{id:usuario,nombre:'Ana Técnica',activo:true}]);if(tabla==='preventivos_realizados')return query(declaraciones);if(tabla==='preventivos_locales')return query(locales);if(tabla==='preventivos_cierres_historial')return query(cierres);if(tabla==='preventivos_ordenes')return query(ordenes);throw Error('Tabla inesperada: '+tabla)},
rpc(nombre,p){
if(nombre==='cambiar_exclusion_orden_preventivo'){if(fallar)return Promise.resolve({error:{message:'Conexión de prueba falló'}});const anterior=exclusiones.find(e=>e.numero_orden===p.p_numero_orden);if((anterior?.revision||0)!==p.p_revision)return Promise.resolve({error:{message:'La exclusión cambió'}});const data={numero_orden:p.p_numero_orden,excluida:p.p_excluida,motivo:p.p_motivo,autor_nombre:'Administrador de prueba',actualizado_en:'2026-10-02T14:00:00Z',revision:p.p_revision+1};exclusiones=exclusiones.filter(e=>e!==anterior);exclusiones.push(data);historialExclusiones.push({...data,id:String(historialExclusiones.length+1),registrado_en:data.actualizado_en});sessionStorage.setItem('exclusiones',JSON.stringify(exclusiones));sessionStorage.setItem('historialExclusiones',JSON.stringify(historialExclusiones));return Promise.resolve({data:copiar(data),error:null})}
if(nombre==='consultar_ordenes_preventivos')return query(ordenes.filter(o=>!exclusiones.some(e=>e.numero_orden===o.numero_orden&&e.excluida)));
if(nombre==='sincronizar_catalogo_preventivos'){for(const l of p.p_locales){const actual=locales.find(a=>a.codigo===l.codigo&&a.marca===l.marca);if(actual)Object.assign(actual,{...(actual.revision_catalogo>0?{}:l),activo_calendario:l.activo,activo:actual.activo_manual??l.activo});}return Promise.resolve({error:null})}
if(nombre==='guardar_local_preventivo'){if(fallar)return Promise.resolve({error:{message:'Conexión de prueba falló'}});const d=p.p_datos,actual=locales.find(l=>l.marca===d.marca&&l.codigo===d.codigo);if(p.p_nuevo&&actual)return Promise.resolve({error:{message:'Ese código ya existe'}});if(!p.p_nuevo&&actual.revision_catalogo!==p.p_revision)return Promise.resolve({error:{message:'La programación cambió'}});const data={...(actual||{activo:true,activo_manual:true,activo_calendario:false,revision_estado:0,origen_manual:true}),...d,meses:[d.mes_base,d.mes_base+4,d.mes_base+8],revision_catalogo:p.p_revision+1};if(actual)Object.assign(actual,data);else locales.push(data);sessionStorage.setItem('locales',JSON.stringify(locales));return Promise.resolve({data:copiar(data),error:null})}
if(nombre==='cambiar_estado_local_preventivo'){if(fallar)return Promise.resolve({data:null,error:{message:'Conexión de prueba falló'}});const actual=locales.find(l=>l.codigo===p.p_codigo&&l.marca===p.p_marca);if(actual.revision_estado!==p.p_revision)return Promise.resolve({error:{message:'Revisión desactualizada'}});Object.assign(actual,{activo:!p.p_cerrado,activo_manual:!p.p_cerrado,fecha_cierre:p.p_cerrado?p.p_fecha:null,motivo_cierre:p.p_motivo,revision_estado:p.p_revision+1});cierres.push({id:String(cierres.length+1),marca:p.p_marca,codigo:p.p_codigo,cerrado:p.p_cerrado,fecha_cierre:actual.fecha_cierre,motivo:p.p_motivo,registrado_en:'2026-10-02T14:00:00Z'});sessionStorage.setItem('locales',JSON.stringify(locales));sessionStorage.setItem('cierres',JSON.stringify(cierres));return Promise.resolve({data:copiar(actual),error:null})}
if(nombre==='marcar_realizado_preventivo'){if(fallar)return Promise.resolve({data:null,error:{message:'Conexión de prueba falló'}});const anterior=declaraciones.find(d=>d.codigo===p.p_codigo&&d.marca===p.p_marca&&d.anio===p.p_anio&&d.mes===p.p_mes);if((anterior?.revision||0)!==p.p_revision)return Promise.resolve({error:{message:'Revisión desactualizada'}});const data={marca:p.p_marca,codigo:p.p_codigo,anio:p.p_anio,mes:p.p_mes,realizado:p.p_realizado,fecha_realizado:p.p_fecha,equipos_declarados:p.p_equipos,observaciones:p.p_observaciones,realizado_nombre:'Ana Técnica',realizado_por:usuario,revision:p.p_revision+1,actualizado_en:'2026-10-02T14:00:00Z'};declaraciones=declaraciones.filter(d=>d!==anterior);declaraciones.push(data);return Promise.resolve({data:copiar(data),error:null})}throw Error('RPC inesperada: '+nombre)}};
`
const compilado=await build({stdin:{contents:'import React from "react";import{createRoot}from"react-dom/client";import App from"./src/App.jsx";import Preventivos from"./src/components/Preventivos.jsx";import*as backend from"./src/supabase.jsx";window.__preventivosTest=backend;createRoot(document.getElementById("root")).render(location.search.includes("modo=admin")?React.createElement("main",{className:"mx-auto max-w-7xl p-4"},React.createElement(Preventivos)):React.createElement(App));',resolveDir:process.cwd(),loader:'jsx'},bundle:true,write:false,outdir:'prueba-en-memoria',jsx:'automatic',format:'iife',define:{'process.env.NODE_ENV':'"production"'},plugins:[{name:'prueba-sin-red',setup(api){
  api.onLoad({filter:/supabase\.jsx$/},()=>({contents:backend,loader:'js'}))
  api.onResolve({filter:/\.xlsx\?url$/},args=>({path:join(args.resolveDir,args.path.replace('?url','')),namespace:'excel-url'}))
  api.onLoad({filter:/.*/,namespace:'excel-url'},async args=>({contents:`export default ${JSON.stringify('data:application/octet-stream;base64,'+(await readFile(args.path)).toString('base64'))}`,loader:'js'}))
}}]})
const js=compilado.outputFiles.find(f=>f.path.endsWith('.js')).text
const cssNombre=(await readFile('dist/index.html','utf8')).match(/href="\/assets\/([^" ]+\.css)"/)[1]
const css=await readFile(join('dist/assets',cssNombre))
const server=createServer((req,res)=>{if(req.url==='/prueba.js'){res.setHeader('Content-Type','application/javascript');res.end(js)}else if(req.url==='/prueba.css'){res.setHeader('Content-Type','text/css');res.end(css)}else{res.setHeader('Content-Type','text/html');res.end('<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/prueba.css"></head><body><div id="root"></div><script src="/prueba.js"></script></body></html>')}})
let browser, pagina
try {
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve))
  browser=await chromium.launch({headless:true,...(process.argv[4]?{executablePath:process.argv[4]}:{})})
  const page=await browser.newPage({viewport:{width:390,height:844}})
  pagina=page
  await page.clock.install({time:new Date('2026-10-02T14:00:00Z')})
  const errores=[];page.on('pageerror',error=>{errores.push(error.message);console.log('Error UI: '+error.message)})
  const puerto=server.address().port
  await page.goto(`http://127.0.0.1:${puerto}/__preventivos_test#preventivos`,{waitUntil:'domcontentloaded'})
  await page.getByRole('heading',{name:'Preventivos',exact:true}).waitFor()
  await page.getByLabel(/^Mes programado/).waitFor()
  await page.getByLabel(/^Restaurantes/).selectOption('GRANJERO')
  const ficha=page.locator('article').filter({hasText:`#${local.codigo}`}).first()
  await ficha.getByRole('button',{name:'Marcar realizado'}).click()
  await page.getByLabel('Equipos trabajados (opcional)').fill('3')
  await page.getByLabel('Observación (opcional)').fill('Preventivo realizado; se trabajaron tres equipos.')
  await page.evaluate(()=>window.__preventivosTest.setFallar(true))
  await page.getByRole('button',{name:'Guardar realizado'}).click()
  await page.getByRole('alert').filter({hasText:'Conexión de prueba falló'}).waitFor()
  assert.equal(await page.getByRole('dialog').count(),1)
  await page.evaluate(()=>window.__preventivosTest.setFallar(false))
  await page.getByRole('button',{name:'Guardar realizado'}).click()
  await ficha.getByRole('button',{name:'Detalle',exact:true}).click()
  await ficha.locator('[id^="detalle-preventivo-"]').getByText('Ana Técnica',{exact:true}).waitFor()
  await ficha.getByText('Pendiente de liquidar',{exact:true}).waitFor()
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth),true,'Sin desbordamiento móvil')
  assert.deepEqual(await page.getByLabel(/^Mostrar/).locator('option').allTextContents(),['Todos','Pendientes','Pendientes de liquidar','Finalizados'])
  await page.getByLabel(/^Mostrar/).selectOption('pendiente')
  assert.equal(await ficha.count(),0,'Una marca manual ya no aparece entre pendientes')
  await page.getByLabel(/^Mostrar/).selectOption('por-liquidar')
  await ficha.getByText('Pendiente de liquidar',{exact:true}).waitFor()
  assert.equal(await ficha.getByRole('button',{name:'Marcar realizado'}).count(),0)
  assert.equal(await ficha.getByRole('button',{name:'Deshacer marca'}).count(),1)
  await page.evaluate(()=>window.scrollTo(0,0))
  await page.screenshot({path:join(process.argv[3],'preventivos-movil.png'),fullPage:true})
  await page.evaluate(({codigo})=>window.__preventivosTest.setOrdenes([
    {numero_orden:'ORD-123',marca:'GRANJERO',codigo,fecha_realizada:'2026-10-01',tecnico:'Carlos Reyes',negocio:'Preventivo',estado:'Asignada a Técnico'},
    {numero_orden:'ORD-124',marca:'GRANJERO',codigo,fecha_realizada:'2026-10-02',tecnico:'Daniel López',negocio:'Preventivo',estado:'En Proceso'},
  ]),local)
  await page.getByRole('button',{name:'Actualizar',exact:true}).click()
  await page.getByLabel(/^Mostrar/).selectOption('finalizado')
  await ficha.getByText('Finalizado',{exact:true}).waitFor()
  const ordenesRegistradas=ficha.getByRole('list',{name:'Órdenes registradas'}).locator('li')
  assert.equal(await ordenesRegistradas.count(),2)
  await ordenesRegistradas.filter({hasText:'ORD-123'}).getByText('Técnico: Carlos Reyes',{exact:true}).waitFor()
  await ordenesRegistradas.filter({hasText:'ORD-123'}).getByText('Fecha realizada: 01/10/2026',{exact:true}).waitFor()
  await ordenesRegistradas.filter({hasText:'ORD-124'}).getByText('Técnico: Daniel López',{exact:true}).waitFor()
  await ordenesRegistradas.filter({hasText:'ORD-124'}).getByText('Fecha realizada: 02/10/2026',{exact:true}).waitFor()
  await ficha.screenshot({path:join(process.argv[3],'preventivo-realizado-detalle.png')})
  assert.equal(await ficha.getByText('Finalizado',{exact:true}).count(),1)
  assert.equal(await ficha.getByText('Pendiente de liquidar',{exact:true}).count(),0,'El Excel reemplaza el estado de la marca manual')
  assert.equal(await ficha.getByRole('button',{name:'Deshacer marca'}).count(),0)
  assert.equal(await page.getByRole('button',{name:/^Excluir orden/}).count(),0,'El técnico no puede excluir órdenes')
  assert.equal(await page.getByRole('button',{name:/^Órdenes excluidas/}).count(),0,'El archivo de exclusiones sólo es administrativo')
  await page.setViewportSize({width:1440,height:1000})
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth),true,'Sin desbordamiento PC')
  await page.screenshot({path:join(process.argv[3],'preventivos-pc.png'),fullPage:true})
  await page.getByLabel(/^Mes programado/).selectOption('6')
  await page.getByLabel(/^Mostrar/).selectOption('todos')
  await ficha.getByRole('button',{name:'Marcar realizado'}).waitFor()
  assert.equal(await page.getByText('Ana Técnica',{exact:true}).count(),0,'No hereda marcas de otro mes')
  assert.equal(await page.getByLabel(/^Restaurantes/).locator('option[value="SICILIANA"]').count(),0)
  assert.equal(await page.locator('article').count(),catalogo.filter(l=>l.activo&&l.marca==='GRANJERO'&&l.meses.includes(6)).length,'El filtro unificado conserva todos los Granjero y Siciliana del mes')
  assert.ok(await page.locator('article[data-restaurante-tipo="SICILIANA"]').count()>0)
  assert.ok(await page.locator('article[data-restaurante-tipo="GRANJERO"]').count()>0)
  const fichasPC=await page.locator('article').evaluateAll(fichas=>fichas.slice(0,2).map(f=>{const r=f.getBoundingClientRect();return {x:r.x,y:r.y}}))
  assert.equal(fichasPC[0].y,fichasPC[1].y,'PC: fichas en columnas')
  assert.ok(fichasPC[1].x>fichasPC[0].x)
  await page.evaluate(()=>window.scrollTo(0,0))
  await page.screenshot({path:join(process.argv[3],'preventivos-pc.png')})
  await page.locator('article').first().scrollIntoViewIfNeeded()
  await page.screenshot({path:join(process.argv[3],'preventivos-pc-fichas.png')})
  await page.setViewportSize({width:390,height:844})
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth),true,'Todas las fichas caben en móvil')
  const fichasMovil=await page.locator('article').evaluateAll(fichas=>fichas.slice(0,2).map(f=>{const r=f.getBoundingClientRect();return {x:r.x,y:r.y}}))
  assert.equal(fichasMovil[0].x,fichasMovil[1].x,'Móvil: una columna')
  assert.ok(fichasMovil[1].y>fichasMovil[0].y)
  await page.getByLabel(/^Restaurantes/).selectOption('CAMPERO')
  assert.equal(await page.locator('article:not([data-restaurante-tipo="CAMPERO"])').count(),0)
  assert.equal(await page.getByRole('button',{name:'Marcar cerrado',exact:true}).count(),0,'El técnico no puede cerrar puntos de venta')
  await page.getByRole('button',{name:/^Cerrados \(/}).click()
  assert.equal(await page.locator('[data-local-cerrado]').count(),catalogo.filter(l=>!l.activo).length)
  assert.equal(await page.getByRole('button',{name:'Reactivar punto de venta'}).count(),0,'El técnico no puede reactivar')
  // Administración: cerrar, reintentar, conservar al recargar y reactivar.
  await page.goto(`http://127.0.0.1:${puerto}/__preventivos_test?modo=admin`,{waitUntil:'domcontentloaded'})
  await page.getByLabel(/^Mes programado/).waitFor()
  await page.getByLabel(/^Mostrar/).selectOption('todos')
  await page.getByLabel('Buscar',{exact:true}).fill(local.codigo)
  await ficha.getByRole('button',{name:'Detalle',exact:true}).click()
  await ficha.getByRole('button',{name:'Marcar cerrado',exact:true}).click()
  await page.getByLabel('Motivo del cierre (opcional)').fill('El punto de venta cerró definitivamente.')
  await page.evaluate(()=>window.__preventivosTest.setFallar(true))
  await page.getByRole('button',{name:'Confirmar cierre'}).click()
  await page.getByRole('alert').filter({hasText:'Conexión de prueba falló'}).waitFor()
  await page.evaluate(()=>window.__preventivosTest.setFallar(false))
  await page.getByRole('button',{name:'Confirmar cierre'}).click()
  await page.getByRole('heading',{name:'Puntos de venta cerrados'}).waitFor()
  await page.getByLabel('Buscar cerrado').fill(local.codigo)
  const archivado=page.locator(`[data-local-cerrado="${local.id}"]`)
  await archivado.getByText('Fecha de cierre: 02/10/2026',{exact:true}).waitFor()
  await archivado.locator('summary').click()
  await archivado.getByText('Orden #ORD-123',{exact:true}).waitFor()
  await archivado.getByText('Técnico: Carlos Reyes',{exact:true}).waitFor()
  await archivado.getByText('Fecha realizada: 01/10/2026',{exact:true}).waitFor()
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'Cerrados sin desbordamiento móvil')
  await page.screenshot({path:join(process.argv[3],'preventivos-cerrados-movil.png'),fullPage:true})
  await page.reload({waitUntil:'domcontentloaded'})
  await page.getByLabel(/^Mes programado/).waitFor()
  await page.getByLabel(/^Mostrar/).selectOption('todos')
  await page.getByLabel('Buscar',{exact:true}).fill(local.codigo)
  assert.equal(await ficha.count(),0,'Volver a cargar y sincronizar el Excel no reactiva la ficha')
  await page.getByRole('button',{name:/^Cerrados \(/}).click()
  await page.getByLabel('Buscar cerrado').fill(local.codigo)
  await archivado.getByRole('button',{name:'Reactivar punto de venta'}).click()
  await page.getByRole('button',{name:'Confirmar reactivación'}).click()
  await archivado.waitFor({state:'detached'})
  await page.getByRole('button',{name:'Programación y seguimiento'}).click()
  await page.getByLabel(/^Mostrar/).selectOption('todos')
  await page.getByLabel('Buscar',{exact:true}).fill(local.codigo)
  await ficha.getByText('Finalizado',{exact:true}).waitFor()
  // Exclusión individual desde el detalle; quitar la última orden devuelve a Pendiente.
  await ficha.getByRole('button',{name:'Detalle',exact:true}).click()
  await ficha.getByRole('button',{name:'Excluir orden ORD-123',exact:true}).click()
  await page.getByLabel('Motivo de la exclusión').fill('Orden cargada de más; no se realizó.')
  await page.getByRole('button',{name:'Confirmar exclusión'}).click()
  await ficha.getByText('1 orden registrada en el Excel',{exact:true}).waitFor()
  await ficha.getByText('Finalizado',{exact:true}).waitFor()
  await ficha.getByRole('button',{name:'Excluir orden ORD-124',exact:true}).click()
  await page.evaluate(()=>window.__preventivosTest.setFallar(true))
  await page.getByRole('button',{name:'Confirmar exclusión'}).click()
  await page.getByRole('alert').filter({hasText:'Conexión de prueba falló'}).waitFor()
  assert.equal(await page.getByRole('dialog').count(),1,'La exclusión fallida mantiene el formulario')
  await page.evaluate(()=>window.__preventivosTest.setFallar(false))
  await page.getByRole('button',{name:'Confirmar exclusión'}).click()
  await ficha.getByText('Pendiente',{exact:true}).waitFor()
  await page.getByRole('button',{name:'Órdenes excluidas (2)',exact:true}).click()
  const excluida=page.locator('[data-orden-excluida="ORD-123"]')
  await excluida.getByText('Orden cargada de más; no se realizó.',{exact:true}).first().waitFor()
  await excluida.locator('summary').click()
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'Archivo de exclusiones sin desbordamiento móvil')
  await page.screenshot({path:join(process.argv[3],'preventivos-excluidas-movil.png'),fullPage:true})
  await page.reload({waitUntil:'domcontentloaded'})
  await page.getByLabel(/^Mes programado/).waitFor()
  // Simula importar de nuevo exactamente las mismas órdenes del archivo antiguo.
  await page.evaluate(()=>window.__preventivosTest.setOrdenes(JSON.parse(sessionStorage.getItem('ordenes'))))
  await page.getByRole('button',{name:'Actualizar',exact:true}).click()
  await page.getByLabel('Buscar',{exact:true}).fill(local.codigo)
  await ficha.getByText('Pendiente',{exact:true}).waitFor()
  await page.getByRole('button',{name:'Órdenes excluidas (2)',exact:true}).click()
  await excluida.getByRole('button',{name:'Restaurar orden ORD-123',exact:true}).click()
  await page.getByRole('button',{name:'Confirmar restauración'}).click()
  await excluida.waitFor({state:'detached'})
  await page.getByRole('button',{name:'Programación y seguimiento',exact:true}).click()
  await page.getByLabel('Buscar',{exact:true}).fill(local.codigo)
  await ficha.getByText('Finalizado',{exact:true}).waitFor()
  // Las dos órdenes del caso original, sin fecha, se pueden excluir desde Por ubicar.
  await page.evaluate(()=>window.__preventivosTest.setOrdenes([...JSON.parse(sessionStorage.getItem('ordenes')),
    ...['407456','407457'].map(numero_orden=>({numero_orden,marca:'CAMPERO',codigo:'632',negocio:'CAMPERO 632',fecha_realizada:null,tecnico:'Técnico de prueba'})),
  ]))
  await page.getByRole('button',{name:'Actualizar',exact:true}).click()
  await page.getByRole('button',{name:'Por ubicar (2)',exact:true}).click()
  await page.getByRole('button',{name:'Excluir orden 407456',exact:true}).click()
  await page.getByRole('button',{name:'Confirmar exclusión'}).click()
  await page.getByRole('button',{name:'Por ubicar (1)',exact:true}).waitFor()
  assert.equal(await page.getByRole('button',{name:'Excluir orden 407456',exact:true}).count(),0)
  await page.getByRole('button',{name:'Excluir orden 407457',exact:true}).click()
  await page.getByRole('button',{name:'Confirmar exclusión'}).click()
  await page.getByText('No hay órdenes pendientes de ubicar.',{exact:true}).waitFor()
  await page.getByRole('button',{name:/^Órdenes excluidas/}).click()
  await page.locator('[data-orden-excluida="407456"]').getByRole('button',{name:'Restaurar orden 407456',exact:true}).click()
  await page.getByRole('button',{name:'Confirmar restauración'}).click()
  await page.getByRole('button',{name:'Por ubicar (1)',exact:true}).click()
  await page.getByRole('button',{name:'Excluir orden 407456',exact:true}).waitFor()
  // Alta manual, reintento, persistencia, edición y colores del PNG mensual.
  await page.getByRole('button',{name:'Nueva tienda',exact:true}).click()
  const alta=page.getByRole('dialog',{name:'Nueva tienda',exact:true})
  await alta.getByLabel('Código de tienda').fill('999001')
  await alta.getByLabel('Nombre de tienda').fill('GRANJERO NUEVO DE PRUEBA')
  await alta.getByLabel('Meses de mantenimiento').selectOption('2')
  await alta.getByLabel('Semana (opcional)').fill('SEMANA 2')
  await alta.getByLabel('Equipos previstos (opcional)').fill('12')
  await alta.getByLabel('Dirección (opcional)').fill('Dirección de la tienda nueva')
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'Formulario móvil sin desbordamiento')
  await page.screenshot({path:join(process.argv[3],'preventivos-nueva-tienda-movil.png')})
  await page.evaluate(()=>window.__preventivosTest.setFallar(true))
  await alta.getByRole('button',{name:'Guardar tienda',exact:true}).click()
  await alta.getByRole('alert').filter({hasText:'Conexión de prueba falló'}).waitFor()
  await page.evaluate(()=>window.__preventivosTest.setFallar(false))
  await alta.getByRole('button',{name:'Guardar tienda',exact:true}).click()
  await page.getByLabel('Buscar',{exact:true}).fill('999001')
  const tiendaNueva=page.locator('article').filter({hasText:'#999001'}).first()
  await tiendaNueva.getByText('GRANJERO NUEVO DE PRUEBA',{exact:true}).waitFor()
  await page.reload({waitUntil:'domcontentloaded'})
  await page.getByLabel('Buscar',{exact:true}).fill('999001')
  await tiendaNueva.getByText('12 equipos previstos',{exact:true}).waitFor()
  await tiendaNueva.locator(':scope > div').first().getByText('Dirección de la tienda nueva',{exact:true}).waitFor()
  // La descarga recibe sólo las fichas visibles: búsqueda, marca, estado y mes.
  await page.getByLabel(/^Restaurantes/).selectOption('GRANJERO')
  await page.getByLabel(/^Mostrar/).selectOption('pendiente')
  const filasExportadas=await page.evaluate(()=>{
    const original=document.createElement.bind(document)
    window.__textosPng=[]
    document.createElement=function(nombre,...args){const elemento=original(nombre,...args);if(nombre==='canvas'){const ctx=elemento.getContext('2d'),fill=ctx.fillText.bind(ctx);ctx.fillText=function(texto,...pos){window.__textosPng.push(String(texto));return fill(texto,...pos)}}return elemento}
    return true
  })
  assert.equal(filasExportadas,true)
  const filtrada=page.waitForEvent('download')
  await page.getByRole('button',{name:'Descargar filtrados PNG',exact:true}).click()
  await (await filtrada).saveAs(join(process.argv[3],'preventivos-filtrado-direccion.png'))
  const textosFiltrados=await page.evaluate(()=>window.__textosPng)
  assert.ok(textosFiltrados.includes('999001'))
  assert.ok(textosFiltrados.includes('Dirección de la tienda nueva'))
  assert.ok(!textosFiltrados.includes(local.codigo),'Una ficha fuera de la búsqueda no se exporta')
  assert.ok(!textosFiltrados.includes('CAMPERO'),'La imagen no añade otras marcas')
  await page.getByLabel(/^Mostrar/).selectOption('finalizado')
  assert.equal(await page.getByRole('button',{name:'Descargar filtrados PNG',exact:true}).isDisabled(),true,'Sin resultados no genera una imagen vacía')
  await page.getByLabel(/^Mostrar/).selectOption('pendiente')
  await page.setViewportSize({width:390,height:844})
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'Filtro y descarga sin desbordamiento móvil')
  await tiendaNueva.screenshot({path:join(process.argv[3],'preventivo-direccion-movil.png')})
  await page.setViewportSize({width:1440,height:1000})
  await tiendaNueva.screenshot({path:join(process.argv[3],'preventivo-direccion-pc.png')})
  await tiendaNueva.getByRole('button',{name:'Detalle',exact:true}).click()
  await tiendaNueva.getByRole('button',{name:'Editar programación',exact:true}).click()
  const editar=page.getByRole('dialog',{name:'Editar programación',exact:true})
  assert.equal(await editar.getByLabel('Código de tienda').isDisabled(),true)
  await editar.getByLabel('Nombre de tienda').fill('GRANJERO NUEVO EDITADO')
  await editar.getByLabel('Meses de mantenimiento').selectOption('3')
  await page.setViewportSize({width:1440,height:1000})
  await page.screenshot({path:join(process.argv[3],'preventivos-editar-tienda-pc.png')})
  await editar.getByRole('button',{name:'Guardar programación',exact:true}).click()
  assert.equal(await tiendaNueva.count(),0,'La tienda sale del mes anterior al cambiar su ciclo')
  await page.getByLabel(/^Mes programado/).selectOption('11')
  await tiendaNueva.getByText('GRANJERO NUEVO EDITADO',{exact:true}).waitFor()
  await page.reload({waitUntil:'domcontentloaded'})
  await page.getByLabel(/^Mes programado/).selectOption('11')
  await page.getByLabel('Buscar',{exact:true}).fill('999001')
  await tiendaNueva.getByText('GRANJERO NUEVO EDITADO',{exact:true}).waitFor()
  await page.getByLabel(/^Mes programado/).selectOption('10')
  await page.getByLabel('Buscar',{exact:true}).fill('')
  await page.getByLabel(/^Restaurantes/).selectOption('GRANJERO')
  const porLiquidar=page.locator('article[data-restaurante-tipo]').filter({hasNotText:`#${local.codigo}`}).filter({hasText:'Pendiente'}).first()
  await porLiquidar.getByRole('button',{name:'Marcar realizado',exact:true}).click()
  await page.getByRole('button',{name:'Guardar realizado',exact:true}).click()
  const descarga=page.waitForEvent('download')
  await page.getByRole('button',{name:'Granjero / Siciliana · PNG',exact:true}).click()
  const png=await descarga
  await png.saveAs(join(process.argv[3],'preventivos-listado-colores.png'))
  assert.ok(png.suggestedFilename().endsWith('.png'))
  await page.getByLabel(/^Mes programado/).selectOption('11')
  await page.getByLabel(/^Mostrar/).selectOption('pendiente')
  await page.getByLabel('Buscar',{exact:true}).fill('413')
  const descargaReal=page.waitForEvent('download')
  await page.getByRole('button',{name:'Descargar filtrados PNG',exact:true}).click()
  await (await descargaReal).saveAs(join(process.argv[3],'preventivos-filtrado-direccion-real.png'))
  // El nuevo punto de venta también está disponible para técnicos, sin altas ni edición.
  await page.goto(`http://127.0.0.1:${puerto}/__preventivos_test#preventivos`,{waitUntil:'domcontentloaded'})
  await page.getByLabel(/^Mes programado/).selectOption('11')
  await page.getByLabel('Buscar',{exact:true}).fill('999001')
  await tiendaNueva.getByText('GRANJERO NUEVO EDITADO',{exact:true}).waitFor()
  assert.equal(await page.getByRole('button',{name:/Nueva tienda|Editar programación/}).count(),0)
  // El portal técnico ve únicamente la orden restaurada del mes, sin botones administrativos.
  await page.goto(`http://127.0.0.1:${puerto}/__preventivos_test#preventivos`,{waitUntil:'domcontentloaded'})
  await page.getByLabel(/^Mes programado/).selectOption('10')
  await page.getByLabel('Buscar',{exact:true}).fill(local.codigo)
  await ficha.getByRole('button',{name:'Detalle',exact:true}).click()
  assert.equal(await page.getByRole('button',{name:'Descargar filtrados PNG',exact:true}).count(),0)
  await ficha.getByText('Orden #ORD-123',{exact:true}).waitFor()
  assert.equal(await ficha.getByText('Orden #ORD-124',{exact:true}).count(),0)
  assert.equal(await page.getByRole('button',{name:/Excluir orden|Restaurar orden|Órdenes excluidas/}).count(),0)
  assert.deepEqual(errores,[])
  console.log('UI verificada: portal técnico, seguimiento, fichas y formularios en PC/móvil, PNG a color, archivo Cerrados, altas y edición persistentes, permisos y reintentos. Backend simulado, sin usar Supabase.')
} catch(error) {
  if(pagina){console.log((await pagina.locator('body').innerText()).slice(0,2000));await pagina.screenshot({path:join(process.argv[3],'preventivos-error-prueba.png')})}
  throw error
} finally { await browser?.close();await new Promise(resolve=>server.close(resolve)) }
