import { useEffect, useMemo, useRef, useState } from 'react'
import { Archive, CalendarCheck, Check, ChevronDown, Download, MapPin, Plus, RefreshCw, Settings, X } from 'lucide-react'
import calendario from '../data/preventivosTrimestrales.json'
import { supabase } from '../supabase.jsx'
import { MESES_PREVENTIVOS } from '../utils/preventivos.js'
import { ESTADOS_PREVENTIVOS, validarRealizado } from '../utils/seguimientoPreventivos.js'
import { MARCAS_TRIMESTRALES, periodoTrimestral, tituloTrimestre, fechaTrimestral, prepararTrimestrales, prepararAvanceTrimestral, datosImagenTrimestral, validarProgramacionTrimestral } from '../utils/preventivosTrimestrales.js'
import { cargarTrimestrales, guardarMarcaTrimestral, guardarTiendaTrimestral, cerrarTiendaTrimestral, ajustarOrdenTrimestral, guardarConfigTrimestral } from '../utils/preventivosTrimestralesPersistencia.js'
import { descargarImagenPreventivos } from '../utils/preventivosImagen.js'
import Dialogo from './Dialogo'

const hoy = () => new Intl.DateTimeFormat('en-CA',{timeZone:'America/Guatemala',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
const colores={pendiente:'bg-slate-100 text-slate-800','por-liquidar':'bg-amber-100 text-amber-900',finalizado:'bg-emerald-100 text-emerald-900'}
const campo='control-field w-full'

export default function PreventivosTrimestrales({ marca, tecnico=false, usuarioId:usuarioPortalId=null }) {
  const [datos,setDatos]=useState({programacion:[],ordenes:[],configuracion:null})
  const [listo,setListo]=useState(false),[cargando,setCargando]=useState(true),[ocupado,setOcupado]=useState(false),[error,setError]=useState(''),[aviso,setAviso]=useState('')
  const [usuarioId,setUsuarioId]=useState(usuarioPortalId)
  const [periodo,setPeriodo]=useState(()=>calendario.filter(p=>p.marca===marca).map(periodoTrimestral).sort().at(-1))
  const [mes,setMes]=useState(''),[estado,setEstado]=useState('todos'),[busqueda,setBusqueda]=useState(''),[vista,setVista]=useState('programacion'),[expandido,setExpandido]=useState(null)
  const [edicion,setEdicion]=useState(null),[corte,setCorte]=useState(hoy)
  const carga=useRef(0)
  async function cargar(silencioso=false) {
    const version=++carga.current
    if(!silencioso)setCargando(true)
    try {
      const [resultado,sesion]=await Promise.all([cargarTrimestrales(marca,calendario,tecnico),supabase.auth.getSession()])
      if(version!==carga.current)return
      setDatos(resultado);setListo(true);setError('');setUsuarioId(usuarioPortalId||sesion.data?.session?.user?.id)
    } catch(fallo) {if(version===carga.current){setListo(false);setError(fallo.message)}}
    finally {if(version===carga.current)setCargando(false)}
  }
  useEffect(()=>{cargar();return()=>{carga.current++}},[marca,tecnico,usuarioPortalId])
  useEffect(()=>{const timer=setInterval(()=>{if(!ocupado&&!edicion&&document.visibilityState==='visible')cargar(true)},60000);return()=>clearInterval(timer)},[marca,tecnico,usuarioPortalId,ocupado,edicion])
  const periodos=useMemo(()=>[...new Set([...calendario.filter(p=>p.marca===marca),...datos.programacion].map(periodoTrimestral))].sort().reverse(),[marca,datos.programacion])
  const [anio,trimestre]=periodo.split(':').map(Number)
  const trimestreTitulo=tituloTrimestre(anio,trimestre)
  const seguimiento=useMemo(()=>prepararTrimestrales(datos.programacion,datos.ordenes),[datos.programacion,datos.ordenes])
  const delPeriodo=seguimiento.registros.filter(r=>periodoTrimestral(r.local)===periodo)
  const coincidencias=delPeriodo.filter(r=>Boolean(r.local.cerrado)===(vista==='cerrados')&&(!mes||Number(r.local.fecha_programada.slice(5,7))===Number(mes))&&`${r.local.codigo} ${r.local.nombre} ${r.local.direccion} ${r.local.municipio}`.toLocaleLowerCase('es').includes(busqueda.toLocaleLowerCase('es')))
  const visibles=coincidencias.filter(r=>estado==='todos'||r.estado===estado)
  const cerrados=delPeriodo.filter(r=>r.local.cerrado)
  const excluidas=datos.ordenes.filter(o=>o.excluida)
  function cambiarPeriodo(valor) {setPeriodo(valor);setMes('');setExpandido(null)}
  async function guardar(form) {
    if(ocupado)return
    setOcupado(true)
    try {
      const {tipo,local,orden}=edicion
      if(tipo==='realizado'||tipo==='deshacer') {
        const reporte=tipo==='realizado'?validarRealizado(form,hoy()):{fecha:null,equipos:null,observaciones:form.observaciones.trim()}
        if(tipo==='deshacer'&&!reporte.observaciones)throw new Error('Indica el motivo de la corrección.')
        await guardarMarcaTrimestral(local,{...reporte,realizado:tipo==='realizado'})
      } else if(tipo==='tienda') {
        const validado=validarProgramacionTrimestral({...form,marca})
        if(local&&validado.id!==local.id)throw new Error('Para otro trimestre crea una ficha nueva. Esta edición sólo cambia la programación de la vuelta actual.')
        await guardarTiendaTrimestral({...form,marca},local)
        cambiarPeriodo(periodoTrimestral(validado));setVista('programacion')
      } else if(tipo==='estado') {await cerrarTiendaTrimestral(local,form.observaciones);setVista(local.cerrado?'programacion':'cerrados')}
      else if(tipo==='config') await guardarConfigTrimestral(marca,form.clientes.split('\n').map(s=>s.trim()).filter(Boolean),form.encabezado)
      else if(tipo==='orden') await ajustarOrdenTrimestral(orden,form.programacion_id,form.excluida,form.observaciones)
      setEdicion(null);setAviso('Cambio guardado.');await cargar(true)
    } finally {setOcupado(false)}
  }
  async function descargar(registros=visibles) {
    setOcupado(true)
    try {await descargarImagenPreventivos(datosImagenTrimestral(registros,marca,trimestreTitulo,mes?MESES_PREVENTIVOS[Number(mes)-1]:'Todo el trimestre'),`preventivos-${marca.toLowerCase()}-${anio}-T${trimestre}${mes?`-${mes}`:''}-filtrados.png`)}
    catch(fallo){setError(fallo.message)}finally{setOcupado(false)}
  }
  async function descargarAvance() {
    const resumen=prepararAvanceTrimestral(delPeriodo,corte)
    setOcupado(true)
    try {await descargarImagenPreventivos({titulo:`Avance de preventivos ${MARCAS_TRIMESTRALES[marca]}`,subtitulo:`${trimestreTitulo} · Corte ${fechaTrimestral(corte)}`,tema:'anaranjado',secciones:[{titulo:'Occidente',anchos:[150,120,150,160,185,150,150,175],encabezados:['Agencia','Asignados','Finalizados','Por liquidar','Equipos en Excel','% realizado','Pendientes','% pendiente'],filas:[['OCCIDENTE',resumen.asignados,resumen.finalizados,resumen.porLiquidar,resumen.equipos,`${resumen.porcentaje.toFixed(2)}%`,resumen.pendientes,`${(100-resumen.porcentaje).toFixed(2)}%`]]}],pie:'% realizado: marcas manuales y Excel, sin duplicar. Equipos: órdenes únicas. El estado de la orden no se filtra.'},`avance-${marca.toLowerCase()}-${anio}-T${trimestre}-${corte}.png`)}
    catch(fallo){setError(fallo.message)}finally{setOcupado(false)}
  }
  return <div className="space-y-5">
    <header className="workspace-hero"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="mb-3 flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-sky-300"><CalendarCheck size={14}/> Mantenimientos · Occidente</p><h1 className="text-3xl font-black">Preventivos {MARCAS_TRIMESTRALES[marca]}</h1><p className="mt-2 max-w-xl text-sm text-slate-300">{tecnico?'Consulta las tiendas pendientes y reporta los equipos trabajados.':'Programación por trimestre, avances y seguimiento de cada tienda.'}</p></div><button type="button" disabled={cargando||ocupado} className="btn-ghost inline-flex min-h-11 items-center gap-2 bg-white text-slate-900" onClick={()=>cargar()}><RefreshCw size={15}/> Actualizar</button></div></header>
    {error&&<div role="alert" className="card space-y-2 border-rose-700 bg-rose-50 p-4 text-sm text-rose-800"><p>{error}</p>{!listo&&<p>{tecnico?'Pide al administrador que revise la activación de este menú.':'Ejecuta completo activar_preventivos_trimestrales.sql en Supabase y pulsa Actualizar. Si ya lo ejecutaste, revisa tu conexión.'}</p>}</div>}
    {aviso&&<p role="status" className="card bg-emerald-50 p-3 text-sm text-emerald-900">{aviso}</p>}
    <div className="card flex flex-wrap items-end justify-between gap-3 p-4"><label className="min-w-0 flex-1 text-xs font-bold">Trimestre<select className={`${campo} mt-1`} value={periodo} onChange={e=>cambiarPeriodo(e.target.value)}>{periodos.map(p=>{const [a,t]=p.split(':');return <option key={p} value={p}>{tituloTrimestre(a,t)}</option>})}</select></label><p className="max-w-lg text-xs leading-relaxed text-slate-600">Las fechas pertenecen a esta vuelta. Un nuevo trimestre tendrá su propio listado; los anteriores se conservan.</p>{!tecnico&&<div className="flex flex-wrap gap-2"><button type="button" className="btn-ghost min-h-11" disabled={!listo||ocupado} onClick={()=>setEdicion({tipo:'config'})}><Settings size={14} className="mr-1 inline"/> Configurar Excel diario</button><button type="button" className="btn-primary min-h-11" disabled={!listo||ocupado} onClick={()=>setEdicion({tipo:'tienda'})}><Plus size={14} className="mr-1 inline"/> Nueva tienda</button></div>}</div>
    {!tecnico&&listo&&!datos.configuracion?.clientes?.length&&<p className="card bg-amber-50 p-4 text-sm text-amber-950">La programación y las marcas manuales ya están disponibles. Para reconocer los finalizados, configura el CLIENTE exacto y el encabezado del código en el Excel diario. Después vuelve a subir el reporte.</p>}
    <nav aria-label={`Vistas de ${MARCAS_TRIMESTRALES[marca]}`} className="flex flex-wrap gap-2">{[['programacion','Programación'],['cerrados',`Cerrados (${cerrados.length})`],...(!tecnico?[['por-ubicar',`Por ubicar (${seguimiento.sinUbicar.length})`],['excluidas',`Órdenes excluidas (${excluidas.length})`]]:[])].map(([id,titulo])=><button key={id} type="button" aria-pressed={vista===id} className={`${vista===id?'btn-primary':'btn-ghost'} min-h-11`} onClick={()=>{setVista(id);setEstado('todos')}}>{titulo}</button>)}</nav>
    {cargando&&!listo&&<p className="card p-5 text-sm">Cargando programación…</p>}
    {listo&&['programacion','cerrados'].includes(vista)&&<>
      <div className="grid grid-cols-3 gap-2 sm:gap-4">{Object.entries(ESTADOS_PREVENTIVOS).map(([id,nombre])=><button key={id} type="button" aria-pressed={estado===id} onClick={()=>setEstado(id)} className={`card min-h-24 p-3 text-left ${estado===id?'ring-2 ring-sky-500':''}`}><span className="block text-[11px] font-bold text-slate-600">{nombre}</span><span className="mt-1 block text-2xl font-black">{coincidencias.filter(r=>r.estado===id).length}</span></button>)}</div>
      <div className="card grid gap-3 p-4 sm:grid-cols-3"><label className="text-xs font-bold">Mes programado<select className={`${campo} mt-1`} value={mes} onChange={e=>setMes(e.target.value)}><option value="">Todo el trimestre</option>{[0,1,2].map(i=>(trimestre-1)*3+i+1).map(m=><option key={m} value={m}>{MESES_PREVENTIVOS[m-1]}</option>)}</select></label><label className="text-xs font-bold">Mostrar<select className={`${campo} mt-1`} value={estado} onChange={e=>setEstado(e.target.value)}><option value="todos">Todos los estados</option>{Object.entries(ESTADOS_PREVENTIVOS).map(([id,n])=><option key={id} value={id}>{n}</option>)}</select></label><label className="text-xs font-bold">Buscar<input className={`${campo} mt-1`} value={busqueda} onChange={e=>setBusqueda(e.target.value)} placeholder="Código, tienda o dirección"/></label><p className="text-xs leading-relaxed text-slate-600 sm:col-span-3">Pendiente: sin orden ni marca. Pendiente de liquidar: marcado manualmente, falta el Excel. Finalizado: ya existe una orden válida, sin importar su estado.</p></div>
      <div className="flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-slate-600">{visibles.length} tiendas · Pendientes primero</p><button type="button" className="btn-ghost inline-flex min-h-11 items-center gap-2" disabled={ocupado||!visibles.length} onClick={()=>descargar()}><Download size={14}/> Descargar filtrados PNG</button></div>
      <div className="grid items-start gap-4 lg:grid-cols-2 2xl:grid-cols-3">{visibles.map(r=> {
        const l=r.local,abierto=expandido===l.id,corregible=l.realizado&&(!tecnico||l.realizado_por===usuarioId)
        return <article key={l.id} className="card min-w-0 overflow-hidden" data-tienda={l.codigo}><div className="space-y-4 p-4"><div><div className="mb-2 flex flex-wrap items-center justify-between gap-2"><p className="text-xs font-black text-sky-700">#{l.codigo} · {MARCAS_TRIMESTRALES[marca]}</p><span className={`rounded-lg px-2 py-1 text-[11px] font-bold ${l.cerrado?'bg-slate-200 text-slate-800':colores[r.estado]}`}>{l.cerrado?'Cerrado':ESTADOS_PREVENTIVOS[r.estado]}</span></div><h2 className="text-base font-black leading-snug">{l.nombre}</h2><p className="mt-2 text-xs font-semibold text-slate-600">Programado: {fechaTrimestral(l.fecha_programada)}</p><p className="mt-1 text-xs text-slate-600">{l.equipos==null?'Sin cantidad prevista':`${l.equipos} equipos previstos`}{l.equipos_declarados!=null&&l.realizado?` · ${l.equipos_declarados} declarados`:''}</p></div><div className="space-y-1 border-y border-slate-300 py-3 text-xs text-slate-600"><p className="break-words leading-relaxed">{l.direccion||'Sin dirección registrada'}</p>{l.realizado&&<p className="break-words">Marcado por: {l.realizado_nombre} · {fechaTrimestral(l.fecha_realizado)}</p>}{r.ordenes.length>0&&<p>{r.ordenes.length} equipos en Excel · {r.ordenes.length} órdenes</p>}</div><div className="flex flex-wrap gap-2">{r.estado==='pendiente'&&!l.cerrado&&<button type="button" className="btn-primary min-h-11 flex-1" disabled={ocupado} onClick={()=>setEdicion({tipo:'realizado',local:l})}><Check size={14} className="mr-1 inline"/> Marcar realizado</button>}<button type="button" className="btn-ghost inline-flex min-h-11 flex-1 items-center justify-center gap-1" aria-expanded={abierto} aria-controls={`detalle-${l.id}`} onClick={()=>setExpandido(abierto?null:l.id)}>Detalle<ChevronDown size={14}/></button></div></div>
          <div id={`detalle-${l.id}`} hidden={!abierto} className="space-y-3 border-t border-slate-300 bg-slate-50 p-4 text-xs"><p className="break-words"><span className="font-bold">Tienda:</span> {l.nombre}</p><p>Código: {l.codigo}{l.marca_tienda?` · ${l.marca_tienda}`:''}</p><p>{l.municipio} · {l.departamento}{l.zona?` · Zona ${l.zona}`:''}</p>{l.archivo_origen&&<p className="break-words text-slate-600">Calendario: {l.archivo_origen}</p>}{l.observaciones&&<p className="whitespace-pre-wrap break-words">{l.observaciones}</p>}{l.cerrado&&<p className="break-words">Motivo del cierre: {l.motivo_cierre}</p>}
            {r.todas.length>0&&<ul aria-label="Órdenes registradas" className="space-y-3">{r.todas.map(o=><li key={o.numero_orden} className={`rounded-lg border border-slate-300 p-3 ${o.excluida?'bg-slate-100':'bg-white'}`}><p className="font-bold">Orden #{o.numero_orden}{o.excluida?' · Excluida':''}</p><p className="mt-1">Técnico: {o.tecnico||'No informado'}</p><p>Fecha realizada: {fechaTrimestral(o.fecha_realizada)}</p>{o.motivo&&<p className="mt-1 break-words">{o.motivo}</p>}{!tecnico&&<button type="button" disabled={ocupado} className="btn-ghost mt-2 min-h-11" onClick={()=>setEdicion({tipo:'orden',orden:o})}>Ajustar / excluir orden</button>}</li>)}</ul>}
            <div className="flex flex-wrap gap-2">{corregible&&!l.cerrado&&<button type="button" className="btn-ghost min-h-11" disabled={ocupado} onClick={()=>setEdicion({tipo:'realizado',local:l})}>Editar reporte</button>}{corregible&&r.estado!=='finalizado'&&!l.cerrado&&<button type="button" className="btn-ghost min-h-11" disabled={ocupado} onClick={()=>setEdicion({tipo:'deshacer',local:l})}>Deshacer marca</button>}{l.direccion&&<a className="btn-ghost inline-flex min-h-11 items-center gap-1" target="_blank" rel="noopener noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(l.direccion)}`}><MapPin size={14}/> Mapa</a>}{!tecnico&&<><button type="button" className="btn-ghost min-h-11" disabled={ocupado} onClick={()=>setEdicion({tipo:'tienda',local:l})}>Editar programación</button><button type="button" className="btn-ghost min-h-11" disabled={ocupado} onClick={()=>setEdicion({tipo:'estado',local:l})}><Archive size={14} className="mr-1 inline"/>{l.cerrado?'Reabrir tienda':'Marcar cerrado'}</button></>}</div>
          </div></article>
      })}</div>{!visibles.length&&<p className="card p-5 text-sm text-slate-600">No hay tiendas con estos filtros.</p>}
      {!tecnico&&vista==='programacion'&&<div className="card flex flex-wrap items-end gap-3 p-4"><label className="text-xs font-bold">Fecha de corte del avance<input type="date" required value={corte} onChange={e=>setCorte(e.target.value)} className={`${campo} mt-1`}/></label><button type="button" disabled={ocupado||!corte||!delPeriodo.length} className="btn-ghost inline-flex min-h-11 items-center gap-2" onClick={descargarAvance}><Download size={14}/> Descargar avance PNG</button><p className="text-xs text-slate-600">Resumen acumulado de esta vuelta, separado de las demás marcas.</p></div>}
    </>}
    {listo&&!tecnico&&['por-ubicar','excluidas'].includes(vista)&&<section className="space-y-3"><p className="card p-4 text-sm text-slate-600">{vista==='por-ubicar'?'Estas órdenes necesitan una tienda y un trimestre confirmado. No se usa la fecha de ingreso. Si se atendió en otra vuelta, puedes asignarla al trimestre al que pertenece.':'Las órdenes excluidas no cuentan, aunque vuelvan a aparecer en otro Excel.'}</p>{(vista==='por-ubicar'?seguimiento.sinUbicar:excluidas).map(o=><article key={o.numero_orden} className="card flex flex-wrap items-center justify-between gap-3 p-4"><div className="min-w-0 break-words text-sm"><p className="font-bold">Orden #{o.numero_orden} · {o.codigo||'Sin código'}</p><p>{o.negocio||'Sin negocio'} · {o.tecnico||'Sin técnico'}</p><p className="text-xs text-slate-600">Fecha realizada: {fechaTrimestral(o.fecha_realizada)}</p></div><button type="button" disabled={ocupado} className="btn-ghost min-h-11" onClick={()=>setEdicion({tipo:'orden',orden:o})}>{vista==='por-ubicar'?'Asignar al trimestre':'Revisar / restaurar'}</button></article>)}</section>}
    {edicion&&<EditorTrimestral seleccion={edicion} marca={marca} periodo={periodo} configuracion={datos.configuracion} programacion={datos.programacion} ocupado={ocupado} guardar={guardar} cerrar={()=>{if(!ocupado)setEdicion(null)}}/>}
  </div>
}

function EditorTrimestral({seleccion,marca,periodo,configuracion,programacion,ocupado,guardar,cerrar}) {
  const {tipo,local,orden}=seleccion
  const [error,setError]=useState('')
  const [form,setForm]=useState(()=>({...local,codigo:local?.codigo||'',nombre:local?.nombre||'',fecha_programada:local?.fecha_programada||`${periodo.split(':')[0]}-${String((Number(periodo.split(':')[1])-1)*3+1).padStart(2,'0')}-01`,direccion:local?.direccion||'',municipio:local?.municipio||'',departamento:local?.departamento||'',equipos:local?.equipos??'',fecha:local?.fecha_realizado||hoy(),observaciones:tipo==='deshacer'||tipo==='estado'?'':local?.observaciones||'',equipos_trabajados:local?.equipos_declarados??'',clientes:(configuracion?.clientes||[]).join('\n'),encabezado:configuracion?.encabezado_codigo||'',programacion_id:orden?.programacion_id||'',excluida:orden?.excluida||false}))
  const actualizar=(clave,valor)=>setForm(f=>({...f,[clave]:valor}))
  const titulos={realizado:'Reportar preventivo realizado',deshacer:'Deshacer marca',tienda:local?'Editar programación':'Nueva tienda',estado:local?.cerrado?'Reabrir tienda':'Marcar tienda cerrada',config:'Configurar Excel diario',orden:'Asignar / ajustar orden'}
  async function enviar(e) {e.preventDefault();setError('');try {await guardar(tipo==='realizado'?{...form,equipos:form.equipos_trabajados}:form)}catch(fallo){setError(fallo.message)}}
  const tiendas=programacion.filter(l=>!orden||!orden.codigo||l.codigo===orden.codigo).sort((a,b)=>b.fecha_programada.localeCompare(a.fecha_programada))
  return <Dialogo titulo={titulos[tipo]} onCerrar={cerrar}><form onSubmit={enviar} className="app-dialog-panel"><header className="app-dialog-header"><div><h2 className="text-lg font-black">{titulos[tipo]}</h2><p className="mt-1 break-words text-xs text-slate-600">{local?`#${local.codigo} · ${local.nombre}`:orden?`Orden #${orden.numero_orden}`:MARCAS_TRIMESTRALES[marca]}</p></div><button type="button" aria-label="Cerrar" className="btn-ghost" disabled={ocupado} onClick={cerrar}><X size={18}/></button></header><div className="app-dialog-body space-y-4">
    {tipo==='realizado'&&<><label className="grid gap-1 text-xs font-bold">Fecha en que se realizó<input type="date" required max={hoy()} value={form.fecha} onChange={e=>actualizar('fecha',e.target.value)} className={campo}/></label><label className="grid gap-1 text-xs font-bold">Equipos trabajados (opcional)<input type="number" min="1" max="500" step="1" value={form.equipos_trabajados} onChange={e=>actualizar('equipos_trabajados',e.target.value)} className={campo}/></label><p className="text-xs text-slate-600">Quedará Pendiente de liquidar hasta que aparezca en el Excel. Se conserva el nombre de quien lo reporta.</p></>}
    {tipo==='tienda'&&<><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-xs font-bold">Código de tienda<input required disabled={Boolean(local)} maxLength={40} value={form.codigo} onChange={e=>actualizar('codigo',e.target.value)} className={campo}/></label><label className="grid gap-1 text-xs font-bold">Fecha programada<input required type="date" value={form.fecha_programada} onChange={e=>actualizar('fecha_programada',e.target.value)} className={campo}/></label></div><label className="grid gap-1 text-xs font-bold">Tienda<input required maxLength={250} value={form.nombre} onChange={e=>actualizar('nombre',e.target.value)} className={campo}/></label><label className="grid gap-1 text-xs font-bold">Dirección<textarea rows={3} maxLength={1000} value={form.direccion} onChange={e=>actualizar('direccion',e.target.value)} className={campo}/></label><div className="grid gap-3 sm:grid-cols-2">{['municipio','departamento'].map(c=><label key={c} className="grid gap-1 text-xs font-bold">{c==='municipio'?'Municipio':'Departamento'}<input maxLength={1000} value={form[c]} onChange={e=>actualizar(c,e.target.value)} className={campo}/></label>)}</div><label className="grid gap-1 text-xs font-bold">Equipos previstos (opcional)<input type="number" min="1" max="500" step="1" value={form.equipos} onChange={e=>actualizar('equipos',e.target.value)} className={campo}/></label><p className="text-xs text-slate-600">Sólo esta vuelta. No se repite automáticamente en los próximos trimestres.</p></>}
    {tipo==='config'&&<><p className="text-sm text-slate-600">Escribe únicamente los clientes que identifican preventivos de esta marca. No uses un cliente general si también aparece en reparaciones normales.</p><label className="grid gap-1 text-xs font-bold">CLIENTE exacto del Excel diario (uno por línea)<textarea rows={4} value={form.clientes} onChange={e=>actualizar('clientes',e.target.value)} className={campo} placeholder="Texto exacto de CLIENTE"/></label><label className="grid gap-1 text-xs font-bold">Encabezado del código de tienda<input required maxLength={100} value={form.encabezado} onChange={e=>actualizar('encabezado',e.target.value)} className={campo} placeholder="Encabezado exacto del Excel diario"/></label><p className="text-xs text-slate-600">Después de guardar vuelve a subir el reporte diario. Se deduplica por N° ORDEN y no se filtra por ESTADO. Si el código falta, se busca una coincidencia exacta del nombre del negocio. Dejar CLIENTE vacío desactiva la detección.</p></>}
    {tipo==='orden'&&<><label className="grid gap-1 text-xs font-bold">Tienda y trimestre<select value={form.programacion_id} onChange={e=>actualizar('programacion_id',e.target.value)} className={campo}><option value="">Según fecha realizada / por ubicar</option>{tiendas.map(l=><option key={l.id} value={l.id}>{tituloTrimestre(l.anio,l.trimestre)} · #{l.codigo} · {l.nombre}</option>)}</select></label><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={form.excluida} onChange={e=>actualizar('excluida',e.target.checked)}/> Excluir esta orden del conteo</label><p className="text-xs text-slate-600">La decisión se conserva en las próximas cargas. Excluir no elimina la orden ni una marca manual.</p></>}
    {['realizado','deshacer','estado','orden'].includes(tipo)&&<label className="grid gap-1 text-xs font-bold">{tipo==='realizado'?'Observación (opcional)':'Motivo del cambio'}<textarea required={tipo!=='realizado'} rows={3} maxLength={1500} value={form.observaciones} onChange={e=>actualizar('observaciones',e.target.value)} className={campo}/></label>}
    {error&&<p role="alert" className="text-sm text-rose-700">{error}</p>}
  </div><footer className="app-dialog-footer"><button type="button" disabled={ocupado} className="btn-ghost min-h-11" onClick={cerrar}>Cancelar</button><button type="submit" disabled={ocupado} className="btn-primary min-h-11">{ocupado?'Guardando…':'Guardar'}</button></footer></form></Dialogo>
}
